### ISSUE TITLE
REX to PTI?

### ISSUE THREAD

**Issue by huphtur** [jaap3/pti-tools#111]
Possible to add REX file converting? Upload `.rex` or `.rx2` file and the app spits out sliced `.pti` file.

**Comment by jaap3** [comment]
I had a little look around, and it seems that the in order to use the rex file format you'll have to get a license: https://www.reasonstudios.com/developer/index.cfm?fuseaction=get_article&article=rextechinfo2

Besides that, there seems to be no JS implementation or documentation about the file format available.

This means it will not be possible to add support for rex files in the foreseeable future, sadly.
